version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  app:
    image: app
    ports:
      - "5020:80"
    depends_on:
      - "postgres"
  gw:
    image: gw
    ports:
      - "5000:80"
  identity:
    image: identity
    ports:
      - "5010:80"
    depends_on:
      - "postgres"
  frontend:
    image: frontend
    ports:
      - "8000:8080"