version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - back
      - front
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: app
    ports:
      - 5020:80
    depends_on:
      - postgres
    networks:
      - back

  gw:
    image: gw
    ports:
      - 5000:80
    networks:
      - front
      - back

  identity:
    image: identity
    ports:
      - 5010:80
    networks:
      - back
    depends_on:
      - "postgres"

  frontend:
    image: frontend
    ports:
      - 8000:8080
    networks:
      - front

networks:
  front:
  back:
    external: false

volumes:
  postgres:
    driver: local