version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - back
      - front
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: app
    ports:
      - 5020:5020
    environment:
      - ASPNETCORE_URLS=http://*:5020
    depends_on:
      - postgres
    networks:
      - back

  gw:
    image: gw
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://*:5000
    networks:
      - front
      - back

  identity:
    image: identity
    ports:
      - 5010:5010
    environment:
      - ASPNETCORE_URLS=http://*:5010
    networks:
      - back
    depends_on:
      - "postgres"

  frontend:
    image: frontend
    ports:
      - 5050:8080
    networks:
      - front

networks:
  front:
  back:
    internal: true

volumes:
  postgres:
    driver: local