services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  app:
    image: app
    ports:
      - "5021:5020"
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: Dockerfile
  gw:
    image: gw
    ports:
      - "5001:5000"
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: Dockerfile
  identity:
    image: identity
    ports:
      - "5011:5010"
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: Dockerfile