apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8080
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
