apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: gw
  name: gw
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gw
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: gw
    spec:
      containers:
        - image: gw
          name: gw
          ports:
            - containerPort: 80
          resources: {}
          imagePullPolicy: Never
      restartPolicy: Always
status: {}
