apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: identity
  name: identity
spec:
  ports:
    - name: "5010"
      port: 5010
      targetPort: 80
  selector:
    io.kompose.service: identity
status:
  loadBalancer: {}
