apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
